# Generated by Django 3.0.8 on 2020-07-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20200711_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='is_speciality',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
